### PR TITLE
test multiple node versions in CI

### PR DESCRIPTION
**Pull request by rtfeldman**
This should reproduce https://github.com/avh4/binwrap/issues/11

@michaelglass made a PR to fix it in https://github.com/avh4/binwrap/pull/12, but there are test failures. This PR should trigger Travis and show which failures are due to code changes in Michael's PR versus changes in what Travis is testing.

### CODE REVIEW

**Comment by michaelglass** [comment]
@rtfeldman that's what I said in the issue, I couldn't reproduce it _within_ this repo but I'm fairly certain it's real...

**Comment by rtfeldman** [comment]
@avh4 I added an `appveyor.yml` file in case you want to enable [AppVeyor](http://appveyor.com/) on this. (AppVeyor is basically Travis for Windows. I've been using it for `node-test-runner` and such.)

**Comment by avh4** [comment]
Replaced with https://github.com/avh4/binwrap/commit/6cd31d6a1d89440a4217704029071c436804a09f  I don't think there's value in adding 22 separate builds when none of them could reproduce any failure.  I simplified it in the linked commit to add 3 (node 6, node 8, and node 10)

**Comment by avh4** [comment]
Thanks!  I think everything's sorted out now.  I'll grab the appveyor.yml from here if it's ever needed in the future!

**Pull request closed without merging**
